import { Drive } from "@/types/all-types";

export async function getDrives(): Promise<Drive[]> {
  // This is where you would make an API call
  // For now, we'll return dummy data
  const events = [
    {
      id: 1,
      title: "City General Hospital Blood Drive",
      organizer: "City General Hospital",
      date: "March 15, 2024",
      time: "9:00 AM - 5:00 PM",
      location: "City General Hospital, Main Building",
      address: "123 Healthcare Ave, Medical District",
      distance: "0.8 km",
      spots: 50,
      registered: 32,
      urgentTypes: ["O-", "B+"],
      image: "https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    },
    {
      id: 2,
      title: "Red Cross Community Blood Drive",
      organizer: "Red Cross",
      date: "March 20, 2024",
      time: "10:00 AM - 4:00 PM",
      location: "Community Center Hall",
      address: "456 Elm Street, Downtown",
      distance: "1.5 km",
      spots: 40,
      registered: 18,
      urgentTypes: ["A+", "AB-"],
      image: "https://www.eventbrite.com/blog/wp-content/uploads/2022/04/hospital-event-promotion-768x351.jpg",
    },
    {
      id: 3,
      title: "University Blood Donation Camp",
      organizer: "University Health Services",
      date: "March 25, 2024",
      time: "8:00 AM - 2:00 PM",
      location: "Campus Auditorium",
      address: "789 College Ave, Campus Area",
      distance: "2.3 km",
      spots: 100,
      registered: 75,
      urgentTypes: ["O-", "A-"],
      image: "https://kmihealthcare.com/system/articles/featured_photos/22/7/2.jpg",
    },
    {
      id: 4,
      title: "Corporate Blood Donation Initiative",
      organizer: "Healthy Life Corp",
      date: "March 30, 2024",
      time: "11:00 AM - 6:00 PM",
      location: "Healthy Life Headquarters",
      address: "101 Innovation Drive, Business District",
      distance: "3.8 km",
      spots: 60,
      registered: 42,
      urgentTypes: ["B-", "AB+"],
      image: "https://www.capgemini.com/wp-content/uploads/2021/04/Capgemini-Healthcare-hero-banner.jpg",
    },
    {
      id: 5,
      title: "Local Blood Drive for Cancer Patients",
      organizer: "Helping Hands Organization",
      date: "April 2, 2024",
      time: "9:30 AM - 3:00 PM",
      location: "Helping Hands Community Center",
      address: "321 Charity Lane, Suburbs",
      distance: "5.2 km",
      spots: 45,
      registered: 29,
      urgentTypes: ["O+", "A-"],
      image: "https://storage.googleapis.com/blogs-images-new/ciscoblogs/1/2024/05/GettyImages-1147479249-Use-in-Perpetuity-Cisco-Partner-Premium-Access-RF-%E2%80%93-Full-Service-770x533.jpg",
    },
    {
      id: 6,
      title: "Youth Club Blood Donation Drive",
      organizer: "Youth for Change",
      date: "April 5, 2024",
      time: "12:00 PM - 7:00 PM",
      location: "Community Park Pavilion",
      address: "654 Parkside Drive, West End",
      distance: "2.0 km",
      spots: 30,
      registered: 21,
      urgentTypes: ["B+", "AB-"],
      image: "https://economymiddleeast.com/cdn-cgi/imagedelivery/Xfg_b7GtigYi5mxeAzkt9w/economymiddleeast.com/2024/09/saudi-global-health-exhibition-1.jpg/w=1200,h=800",
    },
    {
      id: 7,
      title: "Monthly Blood Drive at City Mall",
      organizer: "City Mall Management",
      date: "April 10, 2024",
      time: "9:00 AM - 8:00 PM",
      location: "City Mall, Level 3",
      address: "789 Commerce Blvd, Uptown",
      distance: "1.0 km",
      spots: 80,
      registered: 65,
      urgentTypes: ["A+", "O-"],
      image: "https://eithealth.eu/wp-content/uploads/2019/08/Sparking-ideas-for-healthcare-solutions-in-areas-of-%E2%80%98Bringing-Care-Home%E2%80%99-and-%E2%80%98Real-world-Data%E2%80%99.jpg",
    },
    {
      id: 8,
      title: "Blood Drive for Rare Blood Types",
      organizer: "Rare Blood Initiative",
      date: "April 12, 2024",
      time: "10:00 AM - 4:00 PM",
      location: "Specialty Clinic",
      address: "500 Rare Blood Lane, East Side",
      distance: "4.0 km",
      spots: 25,
      registered: 10,
      urgentTypes: ["AB-", "B-"],
      image: "https://lirp.cdn-website.com/69c0b277/dms3rep/multi/opt/world+blood+donation+day+-+PACE+hospitals-640w.jpg",
    },
    {
      id: 9,
      title: "Regional Blood Donation Event",
      organizer: "Regional Health Association",
      date: "April 15, 2024",
      time: "7:00 AM - 1:00 PM",
      location: "Regional Health Center",
      address: "900 Regional Road, Outskirts",
      distance: "6.5 km",
      spots: 70,
      registered: 50,
      urgentTypes: ["O+", "A+"],
      image: "https://www.healthcareradius.in/cloud/2021/11/15/Medica-pic.jpg",
    },
    {
      id: 10,
      title: "Emergency Blood Drive for Flood Victims",
      organizer: "Disaster Relief Organization",
      date: "April 20, 2024",
      time: "8:00 AM - 6:00 PM",
      location: "Disaster Relief Center",
      address: "100 Relief Ave, Downtown",
      distance: "0.5 km",
      spots: 100,
      registered: 90,
      urgentTypes: ["O-", "AB+"],
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRq3pNnZrZXctDOH0BWWh6XREq6QyrVYqOzmQ&s",
    },
  ];
  
 
  
  return events 
}
